# Name of your application. Used to uniquely configure containers.
service: kamal-first

# Registry configuration â€” set this to your image registry. For Docker Hub use `docker.io`.
registry:
  server: docker.io
  username: ${KAMAL_REGISTRY_USERNAME}
  password: ${KAMAL_REGISTRY_PASSWORD}



proxy:
  ssl: true
  host: app.example.com
  app_port: 8080
  healthcheck:
    interval: 30s
    timeout: 5s
    retries: 3
    path: /health


# Configure builder setup.
builder:
  arch: amd64

env:
  secret:
    - REMOTE_HOST
    - REMOTE_SSH_USER
    - KAMAL_REGISTRY_USERNAME
    - KAMAL_REGISTRY_PASSWORD


